FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir grpcio==1.84.0 protobuf==7.36.2
COPY gateway/ ./gateway/
COPY users.json ./users.json
COPY certs/ ./certs/
EXPOSE 50052
CMD ["python", "-u", "gateway/gateway_server.py"]
