# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\"S\n\rUploadRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\r\n\x05label\x18\x04 \x01(\t\"A\n\x0bUploadReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t\"5\n\x0f\x44ownloadRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"T\n\rDownloadReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x04 \x01(\t\"\x1f\n\x0bListRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"L\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t\x12\r\n\x05owner\x18\x04 \x01(\t\"%\n\tListReply\x12\x18\n\x05\x66iles\x18\x01 \x03(\x0b\x32\t.FileInfo\"3\n\rDeleteRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"/\n\x0b\x44\x65leteReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa9\x01\n\x07Storage\x12&\n\x06Upload\x12\x0e.UploadRequest\x1a\x0c.UploadReply\x12,\n\x08\x44ownload\x12\x10.DownloadRequest\x1a\x0e.DownloadReply\x12 \n\x04List\x12\x0c.ListRequest\x1a\n.ListReply\x12&\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0c.DeleteReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=17
  _globals['_UPLOADREQUEST']._serialized_end=100
  _globals['_UPLOADREPLY']._serialized_start=102
  _globals['_UPLOADREPLY']._serialized_end=167
  _globals['_DOWNLOADREQUEST']._serialized_start=169
  _globals['_DOWNLOADREQUEST']._serialized_end=222
  _globals['_DOWNLOADREPLY']._serialized_start=224
  _globals['_DOWNLOADREPLY']._serialized_end=308
  _globals['_LISTREQUEST']._serialized_start=310
  _globals['_LISTREQUEST']._serialized_end=341
  _globals['_FILEINFO']._serialized_start=343
  _globals['_FILEINFO']._serialized_end=419
  _globals['_LISTREPLY']._serialized_start=421
  _globals['_LISTREPLY']._serialized_end=458
  _globals['_DELETEREQUEST']._serialized_start=460
  _globals['_DELETEREQUEST']._serialized_end=511
  _globals['_DELETEREPLY']._serialized_start=513
  _globals['_DELETEREPLY']._serialized_end=560
  _globals['_STORAGE']._serialized_start=563
  _globals['_STORAGE']._serialized_end=732
# @@protoc_insertion_point(module_scope)
